### ISSUE TITLE
"undefined" error when using index type Starter

### ISSUE THREAD

**Issue by Matrx123** [axilla-io/demo-ui#15]
**Describe the Issue**
Getting "undefined" when Asking a question in query tab when using index type as starter. below is the terminal error.
```
- error unhandledRejection: {
  name: 'PineconeError',
  source: 'server',
  message: "PineconeClient: Error calling query: PineconeError: The requested feature 'Namespaces' is not supported by the current index type 'Starter'.",
  stack: ''
}
```

**To Reproduce**
1. Go to query tab after ingesting the default keyword San Francisco.
2. Click on query button after writing a query.
3. See error toast on bottom left.

**Expected behavior**
Should not throw error.

**Screenshots**
![undefined](https://github.com/axilla-io/demo-ui/assets/34768582/b985f1d9-d92b-48fc-a60d-b8468fbc9f90)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox

**Additional context**
We can simply fix it by using optional chaining (?.) to check for null or undefined.

**Comment by benjreinhart** [comment]
Thank you
