### ISSUE TITLE
axilla.io can’t be reached

### ISSUE THREAD

**Issue by tea-artist** [axilla-io/demo-ui#17]
axilla.io unexpectedly closed the connection.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_CLOSED

**Comment by benjreinhart** [comment]
Hey there, we're in the process of rebranding. We're now located at https://axflow.dev.

We'll be cleaning up some stale references to the old name over the coming days and officially launching the rebrand soon.
